# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_theta <- function(m) {
    .Call('_LDshrinkCUDA_calc_theta', PACKAGE = 'LDshrinkCUDA', m)
}

calcLD_CUDA <- function(hmata, map, m = 85, Ne = 11490.672741, cutoff = 1e-3) {
    .Call('_LDshrinkCUDA_calcLD_CUDA', PACKAGE = 'LDshrinkCUDA', hmata, map, m, Ne, cutoff)
}

calcLD_CUDA_sp <- function(hmata, map, m = 85, Ne = 11490.672741, cutoff = 1e-3) {
    .Call('_LDshrinkCUDA_calcLD_CUDA_sp', PACKAGE = 'LDshrinkCUDA', hmata, map, m, Ne, cutoff)
}

